name: comment_on_pr

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - name: Create comments
      run: |
        cat << EOF > comments
        テストの確認
        - [ ] これはやった？
        EOF

    - name: Post comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.html_url }}
      run:
        gh pr comment -F ./comments "${URL}"