name: comment_on_pr

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Notify Develop Update
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
